

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_breez_sdk_liquid(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackbreez_sdk_liquid(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackbreez_sdk_liquid(void*, int8_t);

void uniffi_breez_sdk_liquid_bindings_fn_free_bindingliquidsdk(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_add_event_listener(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_backup(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_buy_bitcoin(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_check_message(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_disconnect(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_fiat_rates(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_lightning_limits(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_onchain_limits(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_get_info(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_list_fiat_currencies(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_list_payments(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_list_refundables(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_lnurl_auth(
	void* ptr,
	RustBuffer req_data,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_lnurl_pay(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_lnurl_withdraw(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_pay_onchain(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_buy_bitcoin(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_pay_onchain(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_receive_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_refund(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_send_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_receive_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_recommended_fees(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_refund(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_register_webhook(
	void* ptr,
	RustBuffer webhook_url,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_remove_event_listener(
	void* ptr,
	RustBuffer id,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_rescan_onchain_swaps(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_restore(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_send_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_sign_message(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_sync(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_unregister_webhook(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_init_callback_eventlistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_init_callback_logger(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void* uniffi_breez_sdk_liquid_bindings_fn_func_connect(
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_func_default_config(
	RustBuffer network,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_func_parse(
	RustBuffer input,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_liquid_bindings_fn_func_parse_invoice(
	RustBuffer input,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_liquid_bindings_fn_func_set_logger(
	uint64_t logger,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_liquid_bindings_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_liquid_bindings_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_liquid_bindings_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_breez_sdk_liquid_bindings_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_breez_sdk_liquid_bindings_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_breez_sdk_liquid_bindings_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_liquid_bindings_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_liquid_bindings_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_connect(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_default_config(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_parse(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_parse_invoice(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_set_logger(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_add_event_listener(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_backup(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_buy_bitcoin(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_check_message(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_disconnect(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_fiat_rates(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_lightning_limits(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_onchain_limits(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_get_info(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_list_fiat_currencies(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_list_payments(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_list_refundables(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_lnurl_auth(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_lnurl_pay(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_lnurl_withdraw(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_pay_onchain(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_buy_bitcoin(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_pay_onchain(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_receive_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_refund(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_send_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_receive_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_recommended_fees(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_refund(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_register_webhook(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_remove_event_listener(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_rescan_onchain_swaps(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_restore(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_send_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_sign_message(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_sync(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_unregister_webhook(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_eventlistener_on_event(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_logger_log(
	RustCallStatus* out_status
);

uint32_t ffi_breez_sdk_liquid_bindings_uniffi_contract_version(
	RustCallStatus* out_status
);


int32_t breez_sdk_liquid_bindings_cgo_EventListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t breez_sdk_liquid_bindings_cgo_Logger(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

