

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceEventListenerMethod0)(uint64_t uniffi_handle, RustBuffer e, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceEventListenerMethod0(
				UniffiCallbackInterfaceEventListenerMethod0 cb, uint64_t uniffi_handle, RustBuffer e, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, e, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD0
typedef void (*UniffiCallbackInterfaceLoggerMethod0)(uint64_t uniffi_handle, RustBuffer l, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLoggerMethod0(
				UniffiCallbackInterfaceLoggerMethod0 cb, uint64_t uniffi_handle, RustBuffer l, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, l, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD0
typedef void (*UniffiCallbackInterfaceSignerMethod0)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod0(
				UniffiCallbackInterfaceSignerMethod0 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD1
typedef void (*UniffiCallbackInterfaceSignerMethod1)(uint64_t uniffi_handle, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod1(
				UniffiCallbackInterfaceSignerMethod1 cb, uint64_t uniffi_handle, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, derivation_path, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD2
typedef void (*UniffiCallbackInterfaceSignerMethod2)(uint64_t uniffi_handle, RustBuffer msg, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod2(
				UniffiCallbackInterfaceSignerMethod2 cb, uint64_t uniffi_handle, RustBuffer msg, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, derivation_path, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD3
typedef void (*UniffiCallbackInterfaceSignerMethod3)(uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod3(
				UniffiCallbackInterfaceSignerMethod3 cb, uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD4
typedef void (*UniffiCallbackInterfaceSignerMethod4)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod4(
				UniffiCallbackInterfaceSignerMethod4 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD5
typedef void (*UniffiCallbackInterfaceSignerMethod5)(uint64_t uniffi_handle, RustBuffer msg, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod5(
				UniffiCallbackInterfaceSignerMethod5 cb, uint64_t uniffi_handle, RustBuffer msg, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, derivation_path, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD6
typedef void (*UniffiCallbackInterfaceSignerMethod6)(uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod6(
				UniffiCallbackInterfaceSignerMethod6 cb, uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SIGNER_METHOD7
typedef void (*UniffiCallbackInterfaceSignerMethod7)(uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceSignerMethod7(
				UniffiCallbackInterfaceSignerMethod7 cb, uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
typedef struct UniffiVTableCallbackInterfaceEventListener {
    UniffiCallbackInterfaceEventListenerMethod0 onEvent;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceEventListener;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOGGER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOGGER
typedef struct UniffiVTableCallbackInterfaceLogger {
    UniffiCallbackInterfaceLoggerMethod0 log;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceLogger;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_SIGNER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_SIGNER
typedef struct UniffiVTableCallbackInterfaceSigner {
    UniffiCallbackInterfaceSignerMethod0 xpub;
    UniffiCallbackInterfaceSignerMethod1 deriveXpub;
    UniffiCallbackInterfaceSignerMethod2 signEcdsa;
    UniffiCallbackInterfaceSignerMethod3 signEcdsaRecoverable;
    UniffiCallbackInterfaceSignerMethod4 slip77MasterBlindingKey;
    UniffiCallbackInterfaceSignerMethod5 hmacSha256;
    UniffiCallbackInterfaceSignerMethod6 eciesEncrypt;
    UniffiCallbackInterfaceSignerMethod7 eciesDecrypt;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceSigner;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_CLONE_BINDINGLIQUIDSDK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_CLONE_BINDINGLIQUIDSDK
void* uniffi_breez_sdk_liquid_bindings_fn_clone_bindingliquidsdk(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FREE_BINDINGLIQUIDSDK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FREE_BINDINGLIQUIDSDK
void uniffi_breez_sdk_liquid_bindings_fn_free_bindingliquidsdk(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_ACCEPT_PAYMENT_PROPOSED_FEES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_ACCEPT_PAYMENT_PROPOSED_FEES
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_accept_payment_proposed_fees(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_ADD_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_ADD_EVENT_LISTENER
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_add_event_listener(void* ptr, uint64_t listener, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_BACKUP
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_BACKUP
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_backup(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_BUY_BITCOIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_BUY_BITCOIN
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_buy_bitcoin(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_CHECK_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_CHECK_MESSAGE
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_check_message(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_CREATE_BOLT12_INVOICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_CREATE_BOLT12_INVOICE
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_create_bolt12_invoice(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_DISCONNECT
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_disconnect(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_FIAT_RATES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_FIAT_RATES
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_fiat_rates(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_LIGHTNING_LIMITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_LIGHTNING_LIMITS
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_lightning_limits(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_ONCHAIN_LIMITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_ONCHAIN_LIMITS
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_onchain_limits(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_PAYMENT_PROPOSED_FEES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_FETCH_PAYMENT_PROPOSED_FEES
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_fetch_payment_proposed_fees(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_GET_INFO
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_GET_INFO
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_get_info(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_GET_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_GET_PAYMENT
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_get_payment(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LIST_FIAT_CURRENCIES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LIST_FIAT_CURRENCIES
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_list_fiat_currencies(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LIST_PAYMENTS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LIST_PAYMENTS
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_list_payments(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LIST_REFUNDABLES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LIST_REFUNDABLES
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_list_refundables(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LNURL_AUTH
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LNURL_AUTH
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_lnurl_auth(void* ptr, RustBuffer req_data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LNURL_PAY
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_lnurl_pay(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LNURL_WITHDRAW
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_LNURL_WITHDRAW
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_lnurl_withdraw(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PARSE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PARSE
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_parse(void* ptr, RustBuffer input, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PAY_ONCHAIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PAY_ONCHAIN
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_pay_onchain(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_BUY_BITCOIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_BUY_BITCOIN
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_buy_bitcoin(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_LNURL_PAY
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_lnurl_pay(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_PAY_ONCHAIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_PAY_ONCHAIN
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_pay_onchain(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_RECEIVE_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_RECEIVE_PAYMENT
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_receive_payment(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_REFUND
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_REFUND
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_refund(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_PREPARE_SEND_PAYMENT
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_prepare_send_payment(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RECEIVE_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RECEIVE_PAYMENT
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_receive_payment(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RECOMMENDED_FEES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RECOMMENDED_FEES
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_recommended_fees(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_REFUND
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_REFUND
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_refund(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_REGISTER_WEBHOOK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_REGISTER_WEBHOOK
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_register_webhook(void* ptr, RustBuffer webhook_url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_REMOVE_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_REMOVE_EVENT_LISTENER
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_remove_event_listener(void* ptr, RustBuffer id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RESCAN_ONCHAIN_SWAPS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RESCAN_ONCHAIN_SWAPS
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_rescan_onchain_swaps(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RESTORE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_RESTORE
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_restore(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_SEND_PAYMENT
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_send_payment(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_SIGN_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_SIGN_MESSAGE
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_sign_message(void* ptr, RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_SYNC
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_SYNC
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_sync(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_UNREGISTER_WEBHOOK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_METHOD_BINDINGLIQUIDSDK_UNREGISTER_WEBHOOK
void uniffi_breez_sdk_liquid_bindings_fn_method_bindingliquidsdk_unregister_webhook(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
void uniffi_breez_sdk_liquid_bindings_fn_init_callback_vtable_eventlistener(UniffiVTableCallbackInterfaceEventListener* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_INIT_CALLBACK_VTABLE_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_INIT_CALLBACK_VTABLE_LOGGER
void uniffi_breez_sdk_liquid_bindings_fn_init_callback_vtable_logger(UniffiVTableCallbackInterfaceLogger* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_INIT_CALLBACK_VTABLE_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_INIT_CALLBACK_VTABLE_SIGNER
void uniffi_breez_sdk_liquid_bindings_fn_init_callback_vtable_signer(UniffiVTableCallbackInterfaceSigner* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_CONNECT
void* uniffi_breez_sdk_liquid_bindings_fn_func_connect(RustBuffer req, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_CONNECT_WITH_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_CONNECT_WITH_SIGNER
void* uniffi_breez_sdk_liquid_bindings_fn_func_connect_with_signer(RustBuffer req, uint64_t signer, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_DEFAULT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_DEFAULT_CONFIG
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_func_default_config(RustBuffer network, RustBuffer breez_api_key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_PARSE_INVOICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_PARSE_INVOICE
RustBuffer uniffi_breez_sdk_liquid_bindings_fn_func_parse_invoice(RustBuffer input, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_SET_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_FN_FUNC_SET_LOGGER
void uniffi_breez_sdk_liquid_bindings_fn_func_set_logger(uint64_t logger, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_ALLOC
RustBuffer ffi_breez_sdk_liquid_bindings_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_breez_sdk_liquid_bindings_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_FREE
void ffi_breez_sdk_liquid_bindings_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUSTBUFFER_RESERVE
RustBuffer ffi_breez_sdk_liquid_bindings_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U8
void ffi_breez_sdk_liquid_bindings_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U8
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U8
void ffi_breez_sdk_liquid_bindings_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I8
void ffi_breez_sdk_liquid_bindings_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I8
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I8
void ffi_breez_sdk_liquid_bindings_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I8
int8_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U16
void ffi_breez_sdk_liquid_bindings_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U16
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U16
void ffi_breez_sdk_liquid_bindings_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I16
void ffi_breez_sdk_liquid_bindings_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I16
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I16
void ffi_breez_sdk_liquid_bindings_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I16
int16_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U32
void ffi_breez_sdk_liquid_bindings_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U32
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U32
void ffi_breez_sdk_liquid_bindings_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I32
void ffi_breez_sdk_liquid_bindings_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I32
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I32
void ffi_breez_sdk_liquid_bindings_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I32
int32_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_U64
void ffi_breez_sdk_liquid_bindings_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_U64
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_U64
void ffi_breez_sdk_liquid_bindings_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_breez_sdk_liquid_bindings_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_I64
void ffi_breez_sdk_liquid_bindings_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_I64
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_I64
void ffi_breez_sdk_liquid_bindings_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_I64
int64_t ffi_breez_sdk_liquid_bindings_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_F32
void ffi_breez_sdk_liquid_bindings_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_F32
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_F32
void ffi_breez_sdk_liquid_bindings_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_F32
float ffi_breez_sdk_liquid_bindings_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_F64
void ffi_breez_sdk_liquid_bindings_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_F64
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_F64
void ffi_breez_sdk_liquid_bindings_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_F64
double ffi_breez_sdk_liquid_bindings_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_POINTER
void ffi_breez_sdk_liquid_bindings_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_POINTER
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_POINTER
void ffi_breez_sdk_liquid_bindings_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_POINTER
void* ffi_breez_sdk_liquid_bindings_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_breez_sdk_liquid_bindings_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_breez_sdk_liquid_bindings_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_breez_sdk_liquid_bindings_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_POLL_VOID
void ffi_breez_sdk_liquid_bindings_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_CANCEL_VOID
void ffi_breez_sdk_liquid_bindings_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_FREE_VOID
void ffi_breez_sdk_liquid_bindings_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_RUST_FUTURE_COMPLETE_VOID
void ffi_breez_sdk_liquid_bindings_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_CONNECT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_CONNECT_WITH_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_CONNECT_WITH_SIGNER
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_connect_with_signer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_DEFAULT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_DEFAULT_CONFIG
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_default_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_PARSE_INVOICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_PARSE_INVOICE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_parse_invoice(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_SET_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_FUNC_SET_LOGGER
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_func_set_logger(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_ACCEPT_PAYMENT_PROPOSED_FEES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_ACCEPT_PAYMENT_PROPOSED_FEES
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_accept_payment_proposed_fees(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_ADD_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_ADD_EVENT_LISTENER
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_add_event_listener(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_BACKUP
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_BACKUP
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_backup(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_BUY_BITCOIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_BUY_BITCOIN
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_buy_bitcoin(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_CHECK_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_CHECK_MESSAGE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_check_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_CREATE_BOLT12_INVOICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_CREATE_BOLT12_INVOICE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_create_bolt12_invoice(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_DISCONNECT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_FIAT_RATES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_FIAT_RATES
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_fiat_rates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_LIGHTNING_LIMITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_LIGHTNING_LIMITS
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_lightning_limits(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_ONCHAIN_LIMITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_ONCHAIN_LIMITS
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_onchain_limits(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_PAYMENT_PROPOSED_FEES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_FETCH_PAYMENT_PROPOSED_FEES
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_fetch_payment_proposed_fees(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_GET_INFO
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_GET_INFO
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_get_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_GET_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_GET_PAYMENT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_get_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LIST_FIAT_CURRENCIES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LIST_FIAT_CURRENCIES
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_list_fiat_currencies(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LIST_PAYMENTS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LIST_PAYMENTS
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_list_payments(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LIST_REFUNDABLES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LIST_REFUNDABLES
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_list_refundables(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LNURL_AUTH
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LNURL_AUTH
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_lnurl_auth(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LNURL_PAY
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_lnurl_pay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LNURL_WITHDRAW
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_LNURL_WITHDRAW
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_lnurl_withdraw(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PARSE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PARSE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_parse(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PAY_ONCHAIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PAY_ONCHAIN
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_pay_onchain(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_BUY_BITCOIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_BUY_BITCOIN
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_buy_bitcoin(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_LNURL_PAY
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_lnurl_pay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_PAY_ONCHAIN
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_PAY_ONCHAIN
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_pay_onchain(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_RECEIVE_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_RECEIVE_PAYMENT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_receive_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_REFUND
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_REFUND
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_refund(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_PREPARE_SEND_PAYMENT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_prepare_send_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RECEIVE_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RECEIVE_PAYMENT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_receive_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RECOMMENDED_FEES
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RECOMMENDED_FEES
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_recommended_fees(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_REFUND
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_REFUND
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_refund(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_REGISTER_WEBHOOK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_REGISTER_WEBHOOK
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_register_webhook(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_REMOVE_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_REMOVE_EVENT_LISTENER
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_remove_event_listener(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RESCAN_ONCHAIN_SWAPS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RESCAN_ONCHAIN_SWAPS
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_rescan_onchain_swaps(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RESTORE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_RESTORE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_restore(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_SEND_PAYMENT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_send_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_SIGN_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_SIGN_MESSAGE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_sign_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_SYNC
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_SYNC
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_UNREGISTER_WEBHOOK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_BINDINGLIQUIDSDK_UNREGISTER_WEBHOOK
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_bindingliquidsdk_unregister_webhook(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_eventlistener_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_LOGGER_LOG
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_LOGGER_LOG
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_logger_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_XPUB
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_XPUB
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_xpub(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_DERIVE_XPUB
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_DERIVE_XPUB
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_derive_xpub(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_SIGN_ECDSA
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_SIGN_ECDSA
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_sign_ecdsa(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_SIGN_ECDSA_RECOVERABLE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_SIGN_ECDSA_RECOVERABLE
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_sign_ecdsa_recoverable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_SLIP77_MASTER_BLINDING_KEY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_SLIP77_MASTER_BLINDING_KEY
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_slip77_master_blinding_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_HMAC_SHA256
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_HMAC_SHA256
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_hmac_sha256(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_ECIES_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_ECIES_ENCRYPT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_ecies_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_ECIES_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_LIQUID_BINDINGS_CHECKSUM_METHOD_SIGNER_ECIES_DECRYPT
uint16_t uniffi_breez_sdk_liquid_bindings_checksum_method_signer_ecies_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_LIQUID_BINDINGS_UNIFFI_CONTRACT_VERSION
uint32_t ffi_breez_sdk_liquid_bindings_uniffi_contract_version(void
    
);
#endif

 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceEventListenerMethod0(uint64_t uniffi_handle, RustBuffer e, void* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceEventListenerFree(uint64_t handle);
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceLoggerMethod0(uint64_t uniffi_handle, RustBuffer l, void* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceLoggerFree(uint64_t handle);
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod0(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod1(uint64_t uniffi_handle, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod2(uint64_t uniffi_handle, RustBuffer msg, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod3(uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod4(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod5(uint64_t uniffi_handle, RustBuffer msg, RustBuffer derivation_path, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod6(uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerMethod7(uint64_t uniffi_handle, RustBuffer msg, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_liquid_bindings_cgo_dispatchCallbackInterfaceSignerFree(uint64_t handle);
